// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
    // マイグレーションの差分を計算するのに使う空のDB。手元のPostgresを指す（本番には触らない）
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
